[package]
name = "piquant-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
syn = { version = "1.0.107", features = ["full", "extra-traits"] }
proc-macro2 = "1"

[dev-dependencies]
trybuild = { version = "1.0.75", features = ["diff"] }
